# Generated by Django 5.2.4 on 2025-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('US', 'Used'), ('EX', 'Expired'), ('TH', 'Thrown'), ('AV', 'Available')], default='AV', max_length=2),
        ),
    ]
