# Generated by Django 5.2.4 on 2025-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('US', 'Used'), ('EX', 'Expired'), ('TH', 'Thrown')], default='AV', max_length=2),
        ),
    ]
