# Generated by Django 5.2.4 on 2025-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruit'), ('VE', 'Vegetable'), ('MT', 'Meat'), ('DA', 'Dairy'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
