# Generated by Django 5.2.4 on 2026-08-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
